name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: |
          export WECOM_BOT_KEY='${{ secrets.WECOM_BOT_KEY }}';
          cargo test --features=async_api --verbose

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: |
          cargo fmt --all -- --check
